import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box, Typography } from "@mui/material";
import WareHouses from "@/components/warehouses";
import Zones from "@/components/zones";
import Levels from "@/components/breadcrumbs";
import { useContext } from "react";
import { AppContext } from "@/context";
import Aisle from "@/components/aisle";
import Rack from "@/components/rack";
import Shelf from "@/components/shelf";
import Bin from "@/components/bin";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { activeType, activeIndex } = useContext(AppContext);
  console.log(activeType);
  const generateBreadCrumbs = () => {};
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Box
          sx={{
            display: "flex",
            flexDirection: "column",
            width: "100vw",
            height: "100vh",
            background: "white",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <Typography
            variant="h2"
            sx={{
              color: "grey",
              marginBottom: "100px",
            }}
          >
            Bin locator
          </Typography>
          <Levels items={[]} />
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
            }}
          >
            <WareHouses />
            <Zones />
            <Aisle />
            <Rack />
            <Shelf />
            <Bin />
          </Box>
        </Box>
      </main>
    </>
  );
}
